spring:
  profiles:
    active: '@spring.profiles.active@'

  config:
    import: optional:file:.env[.properties]
  application:
    name: todo-appen

  datasource:
    url: jdbc:mysql://localhost:3306/todo_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${TODO_USER}
    password: ${TODO_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

  jackson:
    deserialization:
      fail-on-unknown-properties: true

jwt:
  secret: ${JWT_SECRET}
  expiration-minutes: 30


server:
  port: 8080
  compression.enabled: true
  http2.enabled: true