spring:
  application:
    name: todo-appen

  datasource:
    url: jdbc:mysql://localhost:3306/todo_db?createDatabaseIfNotExist=true
    username: ${todo_user}
    password: ${todo_password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080