spring:

  config:
    import: optional:file:.env[.properties]
  application:
    name: todo-appen

  datasource:
    url: jdbc:mariadb://localhost:3306/todo_db?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${TODO_USER}
    password: ${TODO_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  compression.enabled: true
  http2.enabled: true